# Generated by Django 5.2.8 on 2026-01-03 02:51

import d_autos_app.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('color', models.CharField(default='White', max_length=30)),
                ('mileage', models.IntegerField(default=0, help_text='Current mileage in kilometers')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the car')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(max_length=20)),
                ('license_issue_date', models.DateField()),
                ('license_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee')], default='employee', max_length=20, verbose_name='User Type')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', d_autos_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('sales_agent', 'Sales Agent'), ('mechanic', 'Mechanic'), ('admin', 'Administrator')], max_length=20, verbose_name='Role')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='Emergency Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the rental')),
                ('equipment_gps', models.BooleanField(default=False)),
                ('equipment_child_seat', models.BooleanField(default=False)),
                ('equipment_roof_rack', models.BooleanField(default=False)),
                ('equipment_premium_insurance', models.BooleanField(default=False)),
                ('equipment_driver', models.BooleanField(default=False)),
                ('equipment_wifi', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_autos_app.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_autos_app.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_autos_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Reference number from payment processor', max_length=100, null=True, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment', null=True, verbose_name='Payment Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='d_autos_app.customer', verbose_name='Customer')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='d_autos_app.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reservation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount required for this reservation', max_digits=10)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requirements or requests from the customer')),
                ('additional_equipment', models.CharField(blank=True, help_text='Additional equipment requested (GPS, child seat, etc.)', max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='d_autos_app.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='d_autos_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(default=datetime.date.today, help_text='Date when maintenance is scheduled to start', verbose_name='Scheduled Date')),
                ('completed_date', models.DateField(blank=True, help_text='Date when maintenance was actually completed', null=True, verbose_name='Completed Date')),
                ('next_service_date', models.DateField(blank=True, help_text='Recommended date for next service', null=True, verbose_name='Next Service Date')),
                ('next_service_mileage', models.IntegerField(blank=True, help_text='Recommended mileage for next service', null=True, verbose_name='Next Service Mileage')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('engine_tune', 'Engine Tune-up'), ('transmission', 'Transmission Service'), ('suspension', 'Suspension Repair'), ('electrical', 'Electrical System'), ('air_conditioning', 'Air Conditioning'), ('general_service', 'General Service'), ('body_repair', 'Body Repair'), ('glass_replacement', 'Glass Replacement'), ('interior', 'Interior Repair'), ('exterior', 'Exterior Repair')], default='general_service', help_text='Type of maintenance/service performed', max_length=50, verbose_name='Maintenance Type')),
                ('title', models.CharField(default='General Maintenance Service', help_text='Short description of the maintenance', max_length=200, verbose_name='Maintenance Title')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the maintenance', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the maintenance', max_length=20, verbose_name='Priority')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost of maintenance in Ghana Cedis (₵)', max_digits=10, verbose_name='Total Cost')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Cost of labor only', max_digits=10, null=True, verbose_name='Labor Cost')),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Cost of parts/materials only', max_digits=10, null=True, verbose_name='Parts Cost')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Tax amount included in total', max_digits=10, null=True, verbose_name='Tax Amount')),
                ('parts_used', models.TextField(blank=True, default='', help_text='List of parts and materials used (comma-separated or one per line)', verbose_name='Parts Used')),
                ('parts_quantity', models.TextField(blank=True, default='', help_text='Quantity of each part used', verbose_name='Parts Quantity')),
                ('description', models.TextField(default='Standard maintenance service performed.', help_text='Detailed description of the maintenance work performed', verbose_name='Detailed Description')),
                ('notes', models.TextField(blank=True, default='', help_text='Any additional notes, recommendations, or special instructions', verbose_name='Additional Notes')),
                ('mileage_at_service', models.IntegerField(default=0, help_text='Car mileage when maintenance was performed (in km)', verbose_name='Mileage at Service')),
                ('warranty_period', models.IntegerField(blank=True, default=30, help_text='Warranty period for this service in days', null=True, verbose_name='Warranty Period (days)')),
                ('warranty_expiry_date', models.DateField(blank=True, help_text='Date when warranty for this service expires', null=True, verbose_name='Warranty Expiry Date')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['manager', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenances', to='d_autos_app.employee', verbose_name='Approved By')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='d_autos_app.car', verbose_name='Car')),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['mechanic', 'manager', 'technician']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='d_autos_app.employee', verbose_name='Assigned Mechanic')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-scheduled_date', 'priority'],
                'indexes': [models.Index(fields=['status', 'priority'], name='d_autos_app_status_ddfeb3_idx'), models.Index(fields=['car', 'scheduled_date'], name='d_autos_app_car_id_8088f0_idx'), models.Index(fields=['employee', 'status'], name='d_autos_app_employe_db470d_idx')],
            },
        ),
    ]
