# Generated by Django 5.2.8 on 2026-01-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_autos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the customer'),
        ),
    ]
