# Generated by Django 5.2.8 on 2026-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_autos_app', '0002_customer_date_of_birth_customer_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
