# Generated by Django 5.2.8 on 2026-01-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_autos_app', '0003_alter_customer_address_alter_customer_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
